baseURL = 'https://chei-l.github.io/'
theme = "hugo-blog-awesome"
defaultContentLanguage = "en"

[languages.en]
title = "Chei's blog"
languageName = "English"
languageCode = 'en-us'
weight = 1
[languages.en.params]
sitename = "Chei's blog"
defaultColor = "light"   # set color mode: dark, light, auto
[languages.en.params.author]
avatar = "logo.png" # put the file in assets folder; also ensure that image has same height and width
# Note: image is not rendered if the resource(avatar image) is not found. No error is displayed.
intro = "Chei's blog"
name = "Chei"
description = "Hiya!"
